import os
import subprocess
import hashlib
import json
from nodes.base import BaseNode

class PusherNode(BaseNode):
    def execute(self, state: dict):
        target = state['target_path']
        repo_url = state.get('repo_url', '')
        token = os.getenv("GITHUB_TOKEN")
        branch = state.get('feature_branch', 'agent/surgical-update')
        
        repo_id = hashlib.md5(repo_url.encode()).hexdigest()[:12]
        watermark_file = os.path.abspath(f"workspaces/watermarks/{repo_id}.mtime")
        req_file = os.path.join(target, "requirements.md")

        self.log(f"🚀 Pusher: Preparing PR for {repo_url}...")

        try:
            # 1. Branch and Commit
            subprocess.run(["git", "checkout", "-b", branch], cwd=target, capture_output=True)
            subprocess.run(["git", "add", "."], cwd=target, check=True)
            subprocess.run(["git", "commit", "-m", "🤖 Agent: Verified Implementation"], cwd=target, capture_output=True)

            # 2. Authenticated Push
            auth_url = repo_url.replace("https://", f"https://{token}@")
            subprocess.run(["git", "push", auth_url, branch], cwd=target, check=True)

            # 3. Create PR via Curl (Bypasses Python DNS issues)
            parts = repo_url.rstrip('/').split('/')
            owner_repo = f"{parts[-2]}/{parts[-1].replace('.git', '')}"
            
            self.log(f"📝 Creating PR via Curl for {owner_repo}...")
            api_url = f"https://github.com{owner_repo}/pulls"
            payload = json.dumps({
                "title": "🤖 Agentic Update: Verified CLI Implementation",
                "body": "Automated PR generated by Surgical Watcher.",
                "head": branch,
                "base": "main"
            })

            # Use curl --silent to avoid junk in logs
            curl_cmd = [
                "curl", "--silent", "-X", "POST", api_url,
                "-H", f"Authorization: token {token}",
                "-H", "Accept: application/vnd.github.v3+json",
                "-d", payload
            ]
            
            result = subprocess.run(curl_cmd, capture_output=True, text=True)
            res_data = json.loads(result.stdout)
            
            if "html_url" in res_data:
                self.log(f"✅ PR Created: {res_data.get('html_url')}")
            else:
                self.log(f"⚠️ API Error: {res_data.get('message', 'Unknown')}")

            # 4. Advance Watermark
            if os.path.exists(req_file):
                current_mtime = os.path.getmtime(req_file)
                os.makedirs(os.path.dirname(watermark_file), exist_ok=True)
                with open(watermark_file, "w") as f:
                    f.write(str(current_mtime))
                self.log("✅ Watermark advanced.")

        except Exception as e:
            self.log(f"⚠️ Pusher/PR failed: {e}", level=30)

        return {"next_step": "reporter"}
